server:
  port: 8001

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: Saa08

  # ====SpringAIAlibaba Config=============
  ai:
    dashscope:
      api-key: sk-cae13e65ee4a4e38a244e1810f8e4174

  # ==========redis config ===============
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3s
      timeout: 2s
