server:
  port: 8001

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: Saa09

  # ====SpringAIAlibaba Config=============
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    mcp:
      client:
        # 请求超时时间
        request-timeout: 20s
        # 启用工具回调
        toolcallback:
          enabled: true
        # STDIO服务端配置
        stdio:
          servers-configuration: classpath:/mcp-server.json5

  # ==========redis config ===============
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3s
      timeout: 2s
