server:
  port: 8001

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: Saa03

  # ====SpringAIAlibaba Config=============
  ai:
    dashscope:
      api-key: