server:
  port: 8015

  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: Saa15

  # ====SpringAIAlibaba Config=============
  ai:
    dashscope:
      api-key:

  # ====mcp-client Config=============
    mcp:
      client:
        # 请求超时时间
        request-timeout: 20s
        # 启用工具回调
        toolcallback:
          enabled: true
        # STDIO服务端配置
        stdio:
          servers-configuration: classpath:/mcp-server.json5